version: '3.8'

services:
  db:
    image: postgres:15
    container_name: book-library-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${DB_PORT_FROM}:${DB_PORT_TO}
    volumes:
      - ${DATABASE_PATH}:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    container_name: book-library-api
    command: uvicorn main:app --host ${API_HOST} --port ${API_PORT} --reload
    ports:
      - ${API_PORT_FROM}:${API_PORT}
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:${DB_PORT_TO}/${POSTGRES_DB}
    # volumes:
    #   - .:/app
    depends_on:
      db:
        condition: service_healthy