"""remove num_pages from books

Revision ID: 28275023de38
Revises: 3503b6c6009a
Create Date: 2026-05-19 12:29:52.936282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28275023de38'
down_revision: Union[str, Sequence[str], None] = '3503b6c6009a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'num_pages')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('num_pages', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
