"""add num_pages to books

Revision ID: 3503b6c6009a
Revises: 2d0e5323aa41
Create Date: 2026-05-19 12:22:19.638124

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3503b6c6009a'
down_revision: Union[str, Sequence[str], None] = '2d0e5323aa41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('num_pages', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'num_pages')
    # ### end Alembic commands ###
